# примеры API-запросов

@baseUrl = http://localhost:8000/api
@token_1_admin = 8914d6f0a0dddf40e8570102895efc3e724ca602
@token_2_dim = 01e129a6e83241e0b6e4b182ec08b7808e5ecdf1
@token_3_vik = 34aeda74e7f8c43d22e222c8da5da9f01ba26e9a

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# добавление объявление в избранное для текущего пользователя
POST {{baseUrl}}/advertisements/72/add/
Content-Type: application/json
Authorization: Token {{token_2_dim}}

###

# просмотреть избранные объявления пользователя
GET {{baseUrl}}/advertisements/favorites/
Content-Type: application/json
Authorization: Token {{token_2_dim}}

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token {{token_3_vik}}

{
  "title": "Диван",
  "description": "Черный"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/65/
Content-Type: application/json
Authorization: Token {{token_2_dim}}

{
  "status": "DRAFT",
  "title": "Окно YUFA"
}

###

# попытка удалить объявление
DELETE {{baseUrl}}/advertisements/65/
Content-Type: application/json
Authorization: Token {{token_2_dim}}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json
Authorization: Token {{token_1_admin}}

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2023-03-13
Content-Type: application/json
