# примеры API-запросов

@baseUrl = http://localhost:8000/api
@token_1_admin = 8914d6f0a0dddf40e8570102895efc3e724ca602
@token_2_dim = 01e129a6e83241e0b6e4b182ec08b7808e5ecdf1
@token_3_vik = 34aeda74e7f8c43d22e222c8da5da9f01ba26e9a

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token {{token_3_vik}}

{
  "title": "животные",
  "description": "умные"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/25/
Content-Type: application/json
Authorization: Token {{token_3_vik}}

{
  "status": "CLOSED",
  "title": "Шкаф IKEA"
}

###

# попытка удалить объявление
DELETE {{baseUrl}}/advertisements/24/
Content-Type: application/json
Authorization: Token {{token_2_dim}}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=3
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2020-10-01
Content-Type: application/json
