# Generated by Django 4.1.7 on 2023-03-11 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementFavorites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisements.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('advertisement', 'user')},
            },
        ),
        migrations.AddField(
            model_name='advertisement',
            name='users',
            field=models.ManyToManyField(related_name='favorites', through='advertisements.AdvertisementFavorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
